version: '3.3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=192.168.1.159 ,172.16.160.124,172.16.160.6,13.228.21.41,1.55.215.8
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - ./phpmyadmin/config.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
  kibana:
    build:
      context: ./kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs