version: '3.3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=172.16.160.124,172.16.160.6,13.228.21.41,13.229.228.59
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - ./phpmyadmin/config.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
  kibana:
    build:
      context: ./kibana
    environment:
      SERVER_NAME:${CLIENT_IP}
    ports:
      - "5601:5601"
